name = "Logjam"
uuid = "1d8a39d3-b73b-4a5b-b39c-beddb3604916"
version = "0.2.2"
authors = ["Michael G. Kay <kay@ncsu.edu>"]
description = "Logistics toolkit for facility location, transportation costing, freight road networks (FAF5), route optimization, U.S. geographic data, and GeoMakie visualizations"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LightOSM = "d1922b25-af4e-4ba3-84af-fe9bea896051"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"

[extensions]
LogjamGLMakieExt = "GLMakie"
LogjamOSMExt = ["LightOSM", "NearestNeighbors"]

[compat]
CSV = "0.10"
CairoMakie = "0.12 - 0.15"
DataFrames = "1.6 - 1"
DelaunayTriangulation = "1.1 - 1"
GLMakie = "0.10 - 0.13"
GeoMakie = "0.7"
Graphs = "1.9 - 1"
LightOSM = "0.3"
NearestNeighbors = "0.4"
SimpleWeightedGraphs = "1.4 - 1"
SparseArrays = "1.12.0"
julia = "1.12"

[extras]
LightOSM = "d1922b25-af4e-4ba3-84af-fe9bea896051"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LightOSM", "NearestNeighbors", "SimpleWeightedGraphs", "SparseArrays", "Test"]
