name = "Logjam"
uuid = "1d8a39d3-b73b-4a5b-b39c-beddb3604916"
authors = ["Michael G. Kay <kay@ncsu.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
